function bootstrap(){var N='',tb='" for "gwt:onLoadErrorFn"',rb='" for "gwt:onPropertyErrorFn"',fb='"><\/script>',W='#',Rb='.cache.html',Y='/',Qb=':',lb='::',Zb='<script defer="defer">bootstrap.onInjectionDone(\'bootstrap\')<\/script>',eb='<script id="',ob='=',X='?',Cb='ActiveXObject',qb='Bad handler "',Db='ChromeTab.ChromeFrame',Yb='DOMContentLoaded',Pb="GWT module 'bootstrap' may need to be (re)compiled",gb='SCRIPT',db='__gwt_marker_bootstrap',hb='base',_='baseUrl',Q='begin',O='bootstrap',bb='bootstrap.nocache.js',kb='bootstrap::',Bb='chromeframe',$='clear.cache.gif',nb='content',V='end',Jb='gecko',Kb='gecko1_8',R='gwt.codesvr=',S='gwt.hosted=',T='gwt.hybrid',Sb='gwt/standard/standard.css',sb='gwt:onLoadErrorFn',pb='gwt:onPropertyErrorFn',mb='gwt:property',Xb='head',Nb='hosted.html?bootstrap',Wb='href',Ib='ie6',Hb='ie8',Gb='ie9',ub='iframe',Z='img',vb="javascript:''",Tb='link',Mb='loadExternalRefs',ib='meta',xb='moduleRequested',U='moduleStartup',Fb='msie',jb='name',zb='opera',wb='position:absolute;width:0;height:0;border:none',Ub='rel',Eb='safari',ab='script',Ob='selectingPermutation',P='startup',Vb='stylesheet',cb='undefined',Lb='unknown',yb='user.agent',Ab='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=N,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:O,millis:(new Date).getTime(),type:Q});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(R)!=-1||(c.indexOf(S)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(T)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(O);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return F(a)}}bootstrap=null;c.gwtOnLoad(y,O,s,x);n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:U,millis:(new Date).getTime(),type:V})}}
function C(){function e(a){var b=a.lastIndexOf(W);if(b==-1){b=a.length}var c=a.indexOf(X);if(c==-1){c=a.length}var d=a.lastIndexOf(Y,Math.min(c,b));return d>=0?a.substring(0,d+1):N}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(Z);b.src=a+$;a=e(b.src)}return a}
function g(){var a=E(_);if(a!=null){return a}return N}
function h(){var a=m.getElementsByTagName(ab);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(bb)!=-1){return e(a[b].src)}}return N}
function i(){var a;if(typeof isBodyLoaded==cb||!isBodyLoaded()){var b=db;var c;m.write(eb+b+fb);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=gb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return N}
function j(){var a=m.getElementsByTagName(hb);if(a.length>0){return a[a.length-1].href}return N}
var k=g();if(k==N){k=h()}if(k==N){k=i()}if(k==N){k=j()}if(k==N){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(ib);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(jb),g;if(f){f=f.replace(kb,N);if(f.indexOf(lb)>=0){continue}if(f==mb){g=e.getAttribute(nb);if(g){var h,i=g.indexOf(ob);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=N}t[f]=h}}else if(f==pb){g=e.getAttribute(nb);if(g){try{z=eval(g)}catch(a){alert(qb+g+rb)}}}else if(f==sb){g=e.getAttribute(nb);if(g){try{y=eval(g)}catch(a){alert(qb+g+tb)}}}}}}
function E(a){var b=t[a];return b==null?null:b}
function F(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var G;function H(){if(!G){G=true;var a=m.createElement(ub);a.src=vb;a.id=O;a.style.cssText=wb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:U,millis:(new Date).getTime(),type:xb});a.contentWindow.location.replace(s+J)}}
v[yb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(zb)!=-1}())return zb;if(function(){return c.indexOf(Ab)!=-1||function(){if(c.indexOf(Bb)!=-1){return true}if(typeof window[Cb]!=cb){try{var b=new ActiveXObject(Db);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return Eb;if(function(){return c.indexOf(Fb)!=-1&&m.documentMode>=9}())return Gb;if(function(){return c.indexOf(Fb)!=-1&&m.documentMode>=8}())return Hb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return Ib;if(function(){return c.indexOf(Jb)!=-1}())return Kb;return Lb};u[yb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};bootstrap.onScriptLoad=function(){if(G){q=true;B()}};bootstrap.onInjectionDone=function(){p=true;n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:Mb,millis:(new Date).getTime(),type:V});B()};D();C();var I;var J;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(O))){l.location.reload();return}J=Nb;I=N}n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:O,millis:(new Date).getTime(),type:Ob});if(!A()){try{alert(Pb);return;var K=I.indexOf(Qb);if(K!=-1){x=Number(I.substring(K+1));I=I.substring(0,K)}J=I+Rb}catch(a){return}}var L;function M(){if(!r){r=true;if(!__gwt_stylesLoaded[Sb]){var a=m.createElement(Tb);__gwt_stylesLoaded[Sb]=a;a.setAttribute(Ub,Vb);a.setAttribute(Wb,s+Sb);m.getElementsByTagName(Xb)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Yb,M,false)}if(L){clearInterval(L)}}}
if(m.addEventListener){m.addEventListener(Yb,function(){H();M()},false)}var L=setInterval(function(){if(/loaded|complete/.test(m.readyState)){H();M()}},50);n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:O,millis:(new Date).getTime(),type:V});n&&n({moduleName:O,sessionId:o,subSystem:P,evtGroup:Mb,millis:(new Date).getTime(),type:Q});m.write(Zb)}
bootstrap();